"use client";

import { useEffect, useState } from "react";
import { ShieldAlert, TrendingUp, PieChart as PieIcon, Activity, Loader2, AlertCircle, RefreshCw } from "lucide-react";
import { useDashboard } from "@/context/DashboardContext";

interface LogAnalysis {
  ip_address_or_identifier: string;
  threat_detected:          string;
  details:                  string;
  action:                   string;
}

interface ThreatReport {
  executive_summary: string;
  threat_level:      "Low" | "Medium" | "High" | "Critical";
  log_analyses:      LogAnalysis[];
  error?:            string;
}

const THREAT_COLOR: Record<string, string> = {
  Critical: "#ef4444",
  High:     "#f97316",
  Medium:   "#eab308",
  Low:      "#22c55e",
};

export default function ThreatAnalysisPage() {
  const { activeProject, threatReport, isThreatLoading, runThreatSweep } = useDashboard();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Run sweep when user arrives on this page if:
    // - CSV is uploaded
    // - No report yet OR the stored result was an error (allow retry on navigate)
    const noReport = !threatReport;
    const hasError = threatReport && threatReport.error;
    if (activeProject?.csvUploaded && (noReport || hasError) && !isThreatLoading) {
      setError(null);
      runThreatSweep().catch(e => setError(e.message || "Threat analysis failed."));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeProject?.id, activeProject?.csvUploaded]);

  const handleDownload = () => {
    if (!threatReport) return;
    
    const content = `INSIGHTS - THREAT ANALYSIS REPORT
Created: ${new Date().toLocaleString()}
Project: ${activeProject?.name || "Unknown"}
Threat Level: ${threatReport.threat_level || "Unknown"}

================================================================================
SECURITY INSIGHTS & THREAT VECTORS
================================================================================

${threatReport.log_analyses.map((entry: any, i: number) => `
THREAT #${i + 1}: ${entry.threat_detected}
SOURCE:    ${entry.ip_address_or_identifier}
DETAILS:   ${entry.details}
ACTION:    ${entry.action}
--------------------------------------------------------------------------------`).join('\n')}

Report generated by Insights SOC Assistant.
`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Insights_Threat_Report_${activeProject?.name || "Project"}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  if (!activeProject) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-12 text-center h-full">
         <ShieldAlert className="w-16 h-16 text-gray-700/50 mb-4" />
         <h2 className="text-xl font-medium text-gray-400">Select a project to see analysis</h2>
      </div>
    );
  }

  if (!activeProject.csvUploaded) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-12 text-center h-full">
         <div className="bg-[#161618] border border-border rounded-3xl p-12 max-w-lg shadow-2xl">
           <AlertCircle className="w-16 h-16 text-brand-primary/50 mb-6 mx-auto" />
           <h2 className="text-2xl font-bold text-white mb-3">No Database Indexed</h2>
           <p className="text-gray-400 mb-8 leading-relaxed">
             This project ("{activeProject.name}") has no security logs to analyze. 
             Please go back to the chat and upload a CSV file to initialize the AI engine.
           </p>
           <button 
             onClick={() => window.location.href = "/dashboard"}
             className="px-6 py-2.5 bg-brand-primary text-white rounded-xl font-semibold hover:bg-brand-primary-hover transition-all"
           >
             Go to Dashboard
           </button>
         </div>
      </div>
    );
  }

  return (
    <div className="flex-1 bg-bg-base text-foreground p-8 overflow-y-auto">
      <div className="max-w-5xl mx-auto pb-12">
        
        {/* Header */}
        <div className="flex items-center justify-between gap-4 mb-10">
          <div className="flex items-center gap-4">
            <div className="p-3 rounded-2xl bg-brand-primary/10 border border-brand-primary/20">
              <ShieldAlert className="w-8 h-8 text-brand-primary" />
            </div>
            <div>
              <h1 className="text-3xl font-semibold tracking-tight">Threat Analysis</h1>
              <p className="text-gray-500 text-sm mt-1">Real-time security analytics and behavioral monitoring</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
             <button
                onClick={() => { setError(null); runThreatSweep(); }}
                disabled={isThreatLoading}
                className="flex items-center gap-2 px-4 py-2 rounded-xl border border-border text-gray-400 hover:text-white hover:border-gray-500 transition-all text-sm bg-[#1a1a1d] hover:bg-[#202024] disabled:opacity-50"
              >
                <RefreshCw className={`w-4 h-4 ${isThreatLoading ? "animate-spin" : ""}`} />
                {isThreatLoading ? "Analyzing..." : "Re-run Sweep"}
              </button>
          </div>
        </div>

        {/* Loading */}
        {isThreatLoading && (
          <div className="flex flex-col items-center justify-center py-24 text-center">
            <Loader2 className="w-12 h-12 text-brand-primary animate-spin mb-4" />
            <p className="text-lg text-gray-400 font-medium">Insights is performing behavioral analysis...</p>
            <p className="text-sm text-gray-600 mt-2">Correlating event chains in logs.db...</p>
          </div>
        )}

        {/* Error */}
        {error && !isThreatLoading && (
          <div className="flex items-start gap-3 p-5 bg-red-500/10 border border-red-500/30 rounded-2xl mb-8 overflow-hidden">
            <AlertCircle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold text-red-400 mb-1">Critical Insight Error</p>
              <pre className="text-[10px] font-mono text-red-400/80 leading-relaxed whitespace-pre-wrap overflow-x-auto max-w-full bg-black/20 p-3 rounded-lg">
                {error}
              </pre>
            </div>
          </div>
        )}

        {/* Empty State / Initial Trigger */}
        {!threatReport && !isThreatLoading && !error && (
          <div className="flex flex-col items-center justify-center py-24 text-center">
            <div className="w-20 h-20 rounded-3xl bg-[#161618] border border-border flex items-center justify-center mb-6 shadow-xl">
               <ShieldAlert className="w-10 h-10 text-brand-primary/40" />
            </div>
            <h2 className="text-2xl font-bold text-white mb-3">No Analysis Data</h2>
            <p className="text-gray-400 mb-8 max-w-sm">
              Insights can make mistakes. Verify critical security alerts.
              We haven't performed a security sweep for <strong>{activeProject.name}</strong> yet.
            </p>
            <button 
              onClick={() => { setError(null); runThreatSweep(); }}
              className="px-8 py-3 bg-brand-primary text-white rounded-2xl font-bold hover:bg-brand-primary-hover transition-all shadow-xl flex items-center gap-2"
            >
              <Activity className="w-5 h-5" />
              Perform Threat Sweep
            </button>
          </div>
        )}

        {/* Results UI */}
        {threatReport && (
          <div className={`flex flex-col gap-6 transition-opacity duration-500 ${isThreatLoading ? "opacity-40 pointer-events-none" : "opacity-100"}`}>
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
              
              {/* Severity Card */}
              <div className="lg:col-span-1 bg-[#161618] border border-border rounded-2xl p-8 shadow-xl flex flex-col items-center">
                <div className="w-full flex items-center justify-between mb-8 text-gray-400">
                  <h2 className="text-lg font-medium flex items-center gap-2">
                    <PieIcon className="w-5 h-5 text-brand-primary" />
                    Threat Level
                  </h2>
                </div>

                <div
                  className="w-40 h-40 rounded-full flex items-center justify-center mb-8 border-4"
                  style={{
                    borderColor: THREAT_COLOR[threatReport.threat_level] ?? "#888",
                    boxShadow:   `0 0 30px ${THREAT_COLOR[threatReport.threat_level] ?? "#888"}40`,
                  }}
                >
                  <div className="text-center">
                    <div className="text-3xl font-bold text-white">{threatReport.threat_level}</div>
                    <div className="text-xs text-gray-500 uppercase tracking-widest mt-1">Risk Level</div>
                  </div>
                </div>

                <div className="w-full space-y-3">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-400">Investigated Events</span>
                    <span className="font-medium text-white">{threatReport.log_analyses?.length ?? 0}</span>
                  </div>
                  {Object.entries(THREAT_COLOR).map(([label, color]) => (
                    <div key={label} className="flex items-center justify-between text-sm">
                      <div className="flex items-center gap-2">
                        <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: color }}></div>
                        <span className="text-gray-400">{label}</span>
                      </div>
                      <span className="font-medium text-white" style={{ color: threatReport.threat_level === label ? color : undefined }}>
                        {threatReport.threat_level === label ? (threatReport.log_analyses?.length ?? 0) : 0}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Live Activity Stream */}
              <div className="lg:col-span-2 bg-[#161618] border border-border rounded-2xl p-8 shadow-xl">
                <div className="flex items-center justify-between mb-8">
                  <h2 className="text-lg font-medium flex items-center gap-2 text-white">
                    <Activity className="w-5 h-5 text-brand-primary" />
                    Security Insight Stream
                  </h2>
                  <div className="flex items-center gap-2 text-xs font-medium text-green-500 bg-green-500/10 px-2 py-1 rounded-md border border-green-500/20 animate-pulse">
                    LIVE
                  </div>
                </div>

                <div className="space-y-4 overflow-y-auto max-h-[520px] pr-1 scroll-smooth">
                  {threatReport.log_analyses?.map((entry: any, i: number) => (
                    <div
                      key={i}
                      className="flex gap-4 items-start p-4 hover:bg-white/5 rounded-xl border border-transparent hover:border-border transition-all group"
                    >
                      <div className="p-2 rounded-lg bg-[#0f0f11] group-hover:bg-brand-primary/10 transition-colors shrink-0">
                        <TrendingUp className="w-5 h-5 text-gray-500 group-hover:text-brand-primary" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex justify-between items-start mb-1 gap-2">
                          <h3 className="text-sm font-medium text-white truncate">{entry.threat_detected}</h3>
                          <span
                            className="text-xs font-mono shrink-0 px-2 py-0.5 rounded-full border"
                            style={{
                              color:            THREAT_COLOR[threatReport.threat_level] ?? "#888",
                              borderColor:      `${THREAT_COLOR[threatReport.threat_level] ?? "#888"}40`,
                              backgroundColor:  `${THREAT_COLOR[threatReport.threat_level] ?? "#888"}10`,
                            }}
                          >
                            {entry.ip_address_or_identifier}
                          </span>
                        </div>
                        <p className="text-xs text-gray-400 leading-relaxed mb-2">{entry.details}</p>
                        <p className="text-xs text-brand-primary/80">
                          <span className="font-semibold text-brand-primary text-xs uppercase tracking-tighter mr-1">Recommended Action: </span>
                          {entry.action}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Save Report Button */}
            <div className="flex justify-center mt-4">
               <button 
                onClick={handleDownload}
                className="px-8 py-3 bg-[#1a1a1d] border border-border rounded-2xl text-white font-semibold hover:bg-white/10 hover:border-brand-primary/50 transition-all shadow-xl flex items-center gap-3 group"
               >
                 <ShieldAlert className="w-5 h-5 text-brand-primary group-hover:scale-110 transition-transform" />
                 Save Analysis Report (.txt)
               </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
